const String BASE_URL = 'https://channeli.in/'; //'http://192.168.1.3:60000/';
const String EP_REFRESH_TOKEN = 'token_auth/obtain_pair/';
const String EP_ACCESS_TOKEN = 'token_auth/refresh/';
const String EP_WHO_AM_I = 'kernel/who_am_i/';
const String CONTENT_TYPE_KEY = 'Content-Type';
const String CONTENT_TYPE = 'application/json';
const String AUTHORIZAION_KEY = 'Authorization';
const String AUTHORIZATION_PREFIX = 'Bearer ';
const String NOTICE_DETAIL = 'api/noticeboard/new/';
const String ALL_NOTICES = 'api/noticeboard/new/?page=';
const String STAR_READ = 'api/noticeboard/star_read/';
const String FILTERS_LIST = 'api/noticeboard/filter_list/';
const String PLACEMENT_NOTICES = 'api/noticeboard/filter/?banner=82';
const String IMPORTANT_NOTICES = 'api/noticeboard/new/?important=true&page=';
const String EXPIRED_NOTICES = 'api/noticeboard/old/?page=';
const String BOOKMARKED_NOTICES = 'api/noticeboard/star_filter_view/?page=';
const String NOTIFICATION_EP = 'api/notifications/token/';
